### ISSUE TITLE
Beoordeling opdracht 1.2

### ISSUE THREAD

**Issue by Mennauu** [Zeijls/browser-technologies-1920#1]
Hi Simone,

Niet al je afbeeldingen in de readme worden getoond omdat deze niet gevonden kunnen worden. Ik zou overal even kijken waar deze niet goed ingeladen wordt zodat je het aan kan passen.

**Een beschrijving van alle features die je hebt getest**
Heel netjes uitgewerkt, echt top!

**Een beschrijving van de Devices en browsers waar je op hebt getest**
Fijn dat je afbeeldingen hebt toegevoegd van de devices en de daarop geteste browsers.Je beschrijvingen zijn ook goed!

**Een beschrijving van de screenreader test**
Een beetje beknopt. Misschien leuk om te onderzoeken hoe je je website wel screenreader geschikt zou kunnen maken.

**Beschrijf hoe je de problemen hebt opgelost, of hoe je dit zou oplossen (met todo’s) als je genoeg tijd en budget zou hebben**
Helder beschreven!

--

Echt goed gedaan. Je hebt een zeer fijne readme geschreven!

**Comment by Zeijls** [comment]
Okee dankjewel, ga het aanpassen!
