### ISSUE TITLE
Tussenmomentje

### ISSUE THREAD

**Issue by Mennauu** [Zeijls/browser-technologies-1920#2]
_**Is de opbouw van de readme zo goed?**_

Ziet er prima uit. Heb wel een paar feedbackpuntjes.

- Volgens mij moet `Inhoudspagina` hernoemt worden naar `Inhoudsopgave`.
- Ik zou zelf boven na de zin `Browser Technologies @cmda-minor-web 1920` een omschrijving van de case zetten en vervolgens een afbeelding toevoegen van de website (in z'n huidige staat).
- Installation zou ik wat hoger zetten, waar Feedback nu staat. De stappen van de installation zou ik in een collapsable section zetten.

_**Klopt mijn opbouw in de lagen zoals ik het nu wil aanpakken aan de hand van Progressive Enhancement?**_

Aan de hand van je wireframes wel. Die zijn echt top.

_**Is mijn eerste versie van de HTMl nu netjes opgebouwd op basis van de theorie uit de gelezen artikelen?**_

Als je de artikelen hebt gelezen, dan zou je dat nu dus zelf kunnen beoordelen ;-). Vergeet de aria-labels niet.

**Comment by Zeijls** [comment]
Bedankt voor de feedback! Ik heb alle feedback verwerkt. Moet alleen nog even kijken naar de aria-labels.

**Comment by Zeijls** [comment]
Ook de aria labels toegevoegd!
